CREATE TABLE Game_Board (
    GameId INT NOT NULL,
    BoardId INT NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    PRIMARY KEY (GameId, BoardId),
    CONSTRAINT FK_Game FOREIGN KEY (GameId) REFERENCES Game(Id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_Board FOREIGN KEY (BoardId) REFERENCES Board(Id) ON DELETE CASCADE ON UPDATE CASCADE
);
