CREATE TABLE Player (
    Id INT PRIMARY KEY IDENTITY(1,1) UNIQUE,
    Name VARCHAR(150) NOT NULL,
    Created DATETIME DEFAULT GETDATE(),
    _username VARCHAR(150) NOT NULL UNIQUE,
    _password VARBINARY(64) NOT NULL
);

