CREATE TABLE Player (
    Id INT PRIMARY KEY IDENTITY(1,1) UNIQUE,
    Name VARCHAR(150) NOT NULL,
    Created DATETIME DEFAULT GETDATE(),
    Username VARCHAR(150) NOT NULL UNIQUE,
    PasswordHash VARBINARY(64) NOT NULL
);
